name: Sync with upstream

on:
  schedule:
    - cron: '*/5 * * * *'  # 每天午夜运行

jobs:
  sync-release-branches:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Fetch all branches from upstream
      run: |
        git remote add upstream https://github.com/yunionio/dashboard.git || true  # 添加上游仓库，如果已存在则忽略错误
        git fetch --all

    - name: Sync release branches
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 列出所有看起来像是 release 分支的上游分支
        for branch in $(git branch -r | grep 'upstream/release-'); do
          branch_name=${branch##*/}
          echo "Syncing release branch: $branch_name"
          git checkout "$branch_name" || git checkout --orphan "$branch_name"
          git rebase "upstream/$branch_name"
          git push origin "$branch_name" --force
        done
